[tool.poetry]
name = "uart-test-sw"
version = "0.1.0"
description = ""
authors = ["Paulo Matias <matias@ufscar.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyserial = "^3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
